# Generated by Django 5.2.3 on 2025-10-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
